### ISSUE TITLE
Move to gitter.im

### ISSUE THREAD

**Issue by meeDamian** [lncm/ideas#17]
- [ ] See if makes sense (discuss below or on Wire)
- [ ] create org/account
- [ ] move everyone onto it 😓
- [ ] change all Wire references to gitter

**Comment by AnotherDroog** [comment]
It might not be the most pressing issue right now but it will make onbording much easier in the future. In contrast, getting people into Wire is always going to be a manual process. 

Some more pros/cons

**Pros**:
- @ mentions
- automatic onboarding via link
- github integrations (issue tracking etc)
- more accessible to public
- can create channels inside as needed
- probably uses less memory than Wire client (700MB here)

**Cons**:
- create org once
- everyone needs to sign up or in once
- yet another app or website to open

**Comment by nolim1t** [comment]
wire and keybase .. because encryption.

**Comment by meeDamian** [comment]
Let's stick to Wire, at least until https://github.com/keybase/client/issues/13537 gets resolved…

**Comment by meeDamian** [comment]
The issue above got resolved, and Keybase is working again on my computer 😃.

**Comment by nolim1t** [comment]
So I guess thats a NACK for getting the community over to a new app.

**Comment by AnotherDroog** [comment]
Wire is fine for our needs right now, when the community grows we might want Gitter to let a wider audience communicate easily.

**Comment by meeDamian** [comment]
Closing now.

Can be reopened once we become bigger 'nuff.
