### ISSUE TITLE
lncm website

### ISSUE THREAD

**Issue by nolim1t** [lncm/ideas#22]
Eventually we want to point people to a website which says what we do.

Eventually it should have the following features:

* Static website (for example - Jekyll)
* ipfs with the site pinned on each box (decentralized)

The only thing that maybe isn't decentralized is the domain name which is purely there for seo purposes.

**Comment by AnotherDroog** [comment]
I would like your input on this discussion too @hitchcott 

You mentioned you knew a good alternative static generator?

**Comment by meeDamian** [comment]
Closing, due to existence of https://github.com/lncm/lncm.github.io with it's dedicated issues section.
