### ISSUE TITLE
Get a domain for lncm 

### ISSUE THREAD

**Issue by meeDamian** [lncm/ideas#27]
These are the currently considered options, please comment below:

```
lncm.network
    .club
    .house
    .zone
    .institute
    .soy
    .app
    .run
    .tools
    .co
    .io
    .is
```

edit: replaced broken poll with the list above

**Comment by meeDamian** [comment]
Not sure if that poll above will work well, but let's try… Please don't vote multiple times ^^

**Comment by meeDamian** [comment]
test poll

/polls Option1 'Option 2' "Option 3"

**Comment by nolim1t** [comment]
My picks would be:

.network
.soy (as in street in Thai - ซอย)

but traditionally also would be favored for .co , .is , or .io because they are short. Or can go the really traditional route and pick .org where all OSS projects are.

**Comment by meeDamian** [comment]
From the short ones I prefer `.co`, although I'm not entirely sold on the idea yet.

From all of them my favs are `.zone` & `.institute` (for the same reasons [they] chose that word)

[they]: https://www.paralelnipolis.cz/koncepty/cryptoanarchy-institute/

**Comment by meeDamian** [comment]
Cool, idea, but it's taken 😬

**Comment by meeDamian** [comment]
`lncm.co` is now taken… Let's decide on the best runner up on Wire…

**Comment by meeDamian** [comment]
So… since we got one can this issue be closed now? cc. @AnotherDroog @hitchcott
